### ISSUE TITLE
Academic kittens

### ISSUE THREAD

**Issue by timdp** [kittens/ama#54]
I don't mean to be condescending at all and there was evidently ample reason for Facebook to hire you straight out of high school. That being said, personally, I do feel that university has provided me with some solid foundations which I'm not sure I ever could've picked up any other way. The odd negative experience with people coming from a different background tends to confirm this theory, although I hate to generalize and I sure don't want to insinuate that the same applies to you. Additionally, I'm not ruling out that I could have spent my academic years accumulating other, more useful skills.

So, on to my actual question. Are you combining your job at Facebook with any formal education? If not, do you see yourself doing so in the future?

Sidenote: I used to teach and I'm almost 15 years older than you (and it's a little bizarre to see that written out), so I'm sure we don't entirely share the same views on the software engineering landscape. Again, I'd like to stress that there isn't any condescendence there.

**Comment by kittens** [comment]
No problem! I don't plan on attending any formal education. The only issue it's been is with US immigration but there are other ways which I'm confident I'll be able to take if I want to relocate to the US.

**Comment by timdp** [comment]
Thanks!

**Comment by nikitavoloboev** [comment]
> but there are other ways which I'm confident I'll be able to take if I want to relocate to the US

Can you share these? I also don't have a formal degree and don't plan on getting one (dropped out of CS degree). But I am curious about migrating to US at some point.
